#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          off
yabai -m config window_border_width          4
yabai -m config window_border_radius         12
# yabai -m config active_window_border_color   0xff775759
yabai -m config active_window_border_color   0xfff50057
yabai -m config normal_window_border_color   0x00555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   3

# # set float layout for MBP display
# space_indices_on_mbp_display="$(
# 	yabai -m query --displays \
# 		| jq -e 'map(select(.uuid == "2F917C32-1D54-4830-4A41-1078CDA43226")) | .[0].spaces[]'
# )"
# for index in "$space_indices_on_mbp_display"
# do
# 	yabai -m config --space "$index" layout stack
# done

# debug
yabai -m config debug_output on

echo "yabai configuration loaded.."

